import Link from "next/link";

export default function Footer() {
  return (
    <footer
      style={{
        borderTop: "1px solid var(--color-border)",
        background: "var(--color-bg-secondary)",
        padding: "3rem 0 2rem",
        marginTop: "4rem",
        width: "100%",
        maxWidth: "100vw",
        overflowX: "hidden",
        boxSizing: "border-box",
      }}
    >
      <div className="container-main">
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
            gap: "2rem",
            marginBottom: "2rem",
          }}
        >
          {/* Brand */}
          <div>
            <h3
              style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: "1.1rem",
                fontWeight: 800,
                marginBottom: "0.5rem",
              }}
            >
              Founders North
            </h3>
            <p
              style={{
                fontSize: "0.85rem",
                color: "var(--color-text-tertiary)",
                lineHeight: 1.6,
              }}
            >
              Essential news and deep-dive analysis for founders, operators, and
              business leaders. Curated daily from top industry sources.
            </p>
          </div>

          {/* Navigation */}
          <div>
            <h4
              style={{
                fontSize: "0.8rem",
                fontWeight: 600,
                color: "var(--color-text-tertiary)",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                marginBottom: "0.75rem",
              }}
            >
              Navigation
            </h4>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "0.5rem",
              }}
            >
              <Link
                href="/"
                style={{
                  fontSize: "0.85rem",
                  color: "var(--color-text-secondary)",
                  textDecoration: "none",
                }}
              >
                Home
              </Link>
              <Link
                href="/digests"
                style={{
                  fontSize: "0.85rem",
                  color: "var(--color-text-secondary)",
                  textDecoration: "none",
                }}
              >
                Daily Digests
              </Link>
              <Link
                href="/categories"
                style={{
                  fontSize: "0.85rem",
                  color: "var(--color-text-secondary)",
                  textDecoration: "none",
                }}
              >
                Articles
              </Link>
            </div>
          </div>

          {/* Info */}
          <div>
            <h4
              style={{
                fontSize: "0.8rem",
                fontWeight: 600,
                color: "var(--color-text-tertiary)",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                marginBottom: "0.75rem",
              }}
            >
              About
            </h4>
            <p
              style={{
                fontSize: "0.85rem",
                color: "var(--color-text-tertiary)",
                lineHeight: 1.6,
              }}
            >
              Articles are generated by AI from newsletter content and publicly
              available sources. All original sources are cited.
            </p>
          </div>
        </div>

        <div
          style={{
            borderTop: "1px solid var(--color-border)",
            paddingTop: "1.5rem",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "0.5rem",
          }}
        >
          <p
            style={{
              fontSize: "0.8rem",
              color: "var(--color-text-tertiary)",
            }}
          >
            © {new Date().getFullYear()} Founders North. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
